site_name: Modul 346 - Cloudlösungen konzipieren und realisieren
site_url: "https://oliverlux.github.io/modul346"

nav:
  - 0. Übersicht: index.md
  - 1. Beginn:
    - Start: 1-10.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon-32x32.png  
  language: de
  features:
    - navigation.instant
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - footnotes
  - meta
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 2

extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2021 GBSSG Oliver Lux
extra:
  social:
    - icon: material/home
      link: https://www.gbssg.ch
      name: GBSSG
